# Generated by Django 3.1.1 on 2022-01-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20220110_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job5',
            name='radius',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
